### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by htpvu** [rmap-project/rmap#29]
Including work to:
- [x] update links and documentation from rmap-project to rmap-hub
- [x] document best practices for representing comment types of identifiers #33
- [x] clean up GitHub repo & add documentation for the harvester framework
- [ ] Update technical documentation #32

**Comment by karenhanson** [comment]
remaining documentation work is non-code changes, moved to jira
