### ISSUE TITLE
Search index: Implement a search index to support more robust searching capabilities

### ISSUE THREAD

**Issue by htpvu** [rmap-project/rmap#51]
Currently the GUI and API allows you to search by a specific URI.  It queries the triplestore directly. The search is character and case sensitive. There is no wildcard or best match function and you can’t search literals (non-URIs).  Adding an indexer such as Solr, Lucene, or ElasticSearch over the top of the triplestore would make search more intuitive, faster, and would decrease the load placed on the triplestore to do complex searching.  Much is unknown about how we could implement this. 

The high level tasks could involve. Whoever take on the task of designing and implementing the search index should create implementation tasks according to their design for tracking purpose 

- [x] Write list of requirements/use cases for indexer integration. 
- [x] Read tripplestore and search engine documentation to evaluate options for implementing the indexer against requirements list
- [x] Do some simple tests using the preferred indexer to ensure it is possible to fulfill the necessary requirements
- [x] Develop plan to implement indexer based on evaluation.

**Comment by karenhanson** [comment]
Initial search indexer implemented to satisfy checklist items. Further tasks should be logged separately.
